version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: recipes_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask-app:
    build: .
    container_name: flask_app_1
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data: