version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: recipes_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    command: --local-infile=1 --secure-file-priv=/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-app:
    build: .
    container_name: flask_app_1
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./app/templates:/app/app/templates

volumes:
  db_data:
    driver: local